apiVersion: v1
kind: ConfigMap
metadata:
  name: config-jitsi
data:
  config.js: |
    // https://github.com/jitsi/docker-jitsi-meet/blob/dev/web/rootfs/defaults/config.js
    var config = {
        hosts: {
            domain: 'meet.jitsi',
            muc: 'internal-muc.meet.jitsi',
        },
        bosh: '/http-bind',
        focusUserJid: 'focus@auth.meet.jitsi',
        clientNode: '',
        //webrtcIceUdpDisable: true,
        startScreenSharing: true,
        useNicks: false,
        requireDisplayName: false,
        enableWelcomePage: false,
        defaultLanguage: 'fr',
        noticeMessage: '',
        useStunTurn: true,
        p2p: {
            enabled: true,
            useStunTurn: true,
            stunServers: [
                { urls: 'stun:stun.l.google.com:19302' },
                { urls: 'stun:stun1.l.google.com:19302' },
                { urls: 'stun:stun2.l.google.com:19302' }
            ],
            preferH264: true
        }
    };
  interface_config.js: |
    var interfaceConfig = {
        DEFAULT_BACKGROUND: '#474747',
        DISABLE_VIDEO_BACKGROUND: false,

        INITIAL_TOOLBAR_TIMEOUT: 20000,
        TOOLBAR_TIMEOUT: 4000,
        TOOLBAR_ALWAYS_VISIBLE: false,
        DEFAULT_REMOTE_DISPLAY_NAME: 'Fellow Jitster',
        DEFAULT_LOCAL_DISPLAY_NAME: 'me',
        SHOW_JITSI_WATERMARK: false,
        JITSI_WATERMARK_LINK: '',

        // if watermark is disabled by default, it can be shown only for guests
        SHOW_WATERMARK_FOR_GUESTS: false,
        SHOW_BRAND_WATERMARK: false,
        BRAND_WATERMARK_LINK: '',
        SHOW_POWERED_BY: false,
        SHOW_DEEP_LINKING_IMAGE: false,
        GENERATE_ROOMNAMES_ON_WELCOME_PAGE: false,
        DISPLAY_WELCOME_PAGE_CONTENT: false,
        APP_NAME: 'RendezVous pour se rencontrer en ligne',
        NATIVE_APP_NAME: 'Jitsi Meet',
        PROVIDER_NAME: '',
        LANG_DETECTION: true, // Allow i18n to detect the system language
        INVITATION_POWERED_BY: true,

        AUTHENTICATION_ENABLE: false,

        /**
        * The name of the toolbar buttons to display in the toolbar. If present,
        * the button will display. Exceptions are "livestreaming" and "recording"
        * which also require being a moderator and some values in config.js to be
        * enabled. Also, the "profile" button will not display for user's with a
        * jwt.
        */
        TOOLBAR_BUTTONS: [
            'microphone', 'camera', 'desktop', 'fullscreen',
            'fodeviceselection', 'hangup',
            'livestreaming', 'settings',
            'videoquality', 'filmstrip', 'feedback'
        ],

        SETTINGS_SECTIONS: [ 'devices', 'language' ],
        VIDEO_LAYOUT_FIT: 'both',
        filmStripOnly: false,
        VERTICAL_FILMSTRIP: true,

        CLOSE_PAGE_GUEST_HINT: false,
        RANDOM_AVATAR_URL_PREFIX: false,
        RANDOM_AVATAR_URL_SUFFIX: false,
        FILM_STRIP_MAX_HEIGHT: 120,
        ENABLE_FEEDBACK_ANIMATION: false,
        DISABLE_FOCUS_INDICATOR: false,
        DISABLE_DOMINANT_SPEAKER_INDICATOR: false,
        DISABLE_TRANSCRIPTION_SUBTITLES: false,
        DISABLE_RINGING: false,
        AUDIO_LEVEL_PRIMARY_COLOR: 'rgba(255,255,255,0.4)',
        AUDIO_LEVEL_SECONDARY_COLOR: 'rgba(255,255,255,0.2)',
        POLICY_LOGO: null,
        LOCAL_THUMBNAIL_RATIO: 16 / 9, // 16:9
        REMOTE_THUMBNAIL_RATIO: 1, // 1:1
        LIVE_STREAMING_HELP_LINK: 'https://jitsi.org/live',
        MOBILE_APP_PROMO: true,
        MAXIMUM_ZOOMING_COEFFICIENT: 1.3,
        SUPPORT_URL: 'https://github.com/jitsi/jitsi-meet/issues/new',
        CONNECTION_INDICATOR_AUTO_HIDE_ENABLED: true,
        CONNECTION_INDICATOR_AUTO_HIDE_TIMEOUT: 5000,
        CONNECTION_INDICATOR_DISABLED: false,
        VIDEO_QUALITY_LABEL_DISABLED: false,
        RECENT_LIST_ENABLED: true,
        OPTIMAL_BROWSERS: [ 'chrome', 'chromium', 'firefox', 'nwjs', 'electron' ],
        UNSUPPORTED_BROWSERS: [],
        AUTO_PIN_LATEST_SCREEN_SHARE: 'remote-only'
    };