apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: jitsi
  name: jitsi
  namespace: jitsi
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      k8s-app: jitsi
  template:
    metadata:
      labels:
        k8s-app: jitsi
    spec:
      hostNetwork: true
      containers:
        - name: jicofo
          image: jitsi/jicofo
          imagePullPolicy: Always
          env:
            - name: JICOFO_AUTH_USER
              value: focus
            - name: JICOFO_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JICOFO_AUTH_PASSWORD
            - name: JICOFO_COMPONENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JICOFO_COMPONENT_SECRET
            - name: XMPP_SERVER
              value: localhost
            - name: XMPP_DOMAIN
              value: meet.jitsi
            - name: XMPP_AUTH_DOMAIN
              value: auth.meet.jitsi
            - name: XMPP_INTERNAL_MUC_DOMAIN
              value: internal-muc.meet.jitsi
            - name: TZ
              value: America/Los_Angeles
            - name: JVB_BREWERY_MUC
              value: jvbbrewery
        - name: prosody
          volumeMounts:
          - name: config-prosody
            mountPath: /usr/lib/prosody/modules/mod_turncredentials.lua
            subPath: mod_turncredentials.lua
          - name: config-prosody
            mountPath: /config/conf.d/turncredentials.cfg.lua
            subPath: turncredentials.cfg.lua
          image: jitsi/prosody
          imagePullPolicy: Always
          env:
            - name: XMPP_MODULES
              value: turncredentials
            - name: JICOFO_AUTH_USER
              value: focus
            - name: JICOFO_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JICOFO_AUTH_PASSWORD
            - name: JICOFO_COMPONENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JICOFO_COMPONENT_SECRET
            - name: JVB_AUTH_USER
              value: jvb
            - name: JVB_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JVB_AUTH_PASSWORD
            - name: XMPP_AUTH_DOMAIN
              value: auth.meet.jitsi
            - name: XMPP_DOMAIN
              value: meet.jitsi
            - name: XMPP_INTERNAL_MUC_DOMAIN
              value: internal-muc.meet.jitsi
            - name: XMPP_MUC_DOMAIN
              value: muc.meet.jitsi
            - name: TZ
              value: America/Los_Angeles
        - name: web
          image: jitsi/web
          imagePullPolicy: Always
          volumeMounts:
          - name: config-jitsi
            mountPath: /config/interface_config.js
            subPath: interface_config.js
          - name: config-jitsi
            mountPath: /config/config.js
            subPath: config.js
          ports:
          - containerPort: 80
          env:
            - name: JICOFO_AUTH_USER
              value: focus
            - name: DISABLE_HTTPS
              value: "1"
            - name: XMPP_DOMAIN
              value: meet.jitsi
            - name: XMPP_AUTH_DOMAIN
              value: auth.meet.jitsi
            - name: XMPP_BOSH_URL_BASE
              value: http://127.0.0.1:5280
            - name: XMPP_MUC_DOMAIN
              value: muc.meet.jitsi
            - name: TZ
              value: America/Los_Angeles
        - name: jvb
          image: jitsi/jvb
          imagePullPolicy: Always
      - name: jvb
          volumeMounts:
          - name: config-jvb
            mountPath: /config/sip-communicator.properties
            subPath: sip-communicator.properties
          ports:
          - containerPort: 10000
            hostPort: 10000
            protocol: TCP
          - containerPort: 10000
            hostPort: 10000
            protocol: UDP
          env:
            - name: DOCKER_HOST_ADDRESS
              value: <Set the address for any node in the cluster here>
            - name: JVB_AUTH_USER
              value: jvb
            - name: JVB_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JVB_AUTH_PASSWORD
            - name: JVB_BREWERY_MUC
              value: jvbbrewery
            - name: JVB_PORT
              value: "30300"
            - name: JVB_STUN_SERVERS
              value: stun.l.google.com:19302,stun1.l.google.com:19302,stun2.l.google.com:19302
            - name: JVB_TCP_HARVESTER_DISABLED
              value: "true"
            - name: JVB_TCP_PORT
              value: "4443"
            - name: TZ
              value: America/Los_Angeles
            - name: XMPP_AUTH_DOMAIN
              value: auth.meet.jitsi
            - name: XMPP_INTERNAL_MUC_DOMAIN
              value: internal-muc.meet.jitsi
            - name: XMPP_SERVER
              value: localhost
