apiVersion: v1
kind: Service
metadata:
  labels:
    service: web
  name: web
  namespace: jitsi
spec:
  ports:
  - name: "http"
    port: 80
    targetPort: 80
  selector:
    k8s-app: jitsi
---
 apiVersion: networking.k8s.io/v1beta1
 kind: Ingress
 metadata:
   name: jitsi
   namespace: jitsi
 spec:
  rules:
  - host: ...
    http:
      paths:
      - path: /
        backend:
          serviceName: web
          servicePort: http
  tls:
  - hosts:
    - ...
    secretName: ...